name: Envoi de mail depuis le formulaire

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Vérification du dépôt
      uses: actions/checkout@v2

    - name: Envoi du mail
      uses: dawidd6/action-send-mail@v3
      with:
        connection_url: ${{ secrets.MAIL_CONNECTION }}
        # Required mail server address if not connection_url:
        server_address: outlook.office365.com
        # Server port, default 587:
        server_port: 587
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional (recommended) mail server username:
        username: ${{ secrets.EMAIL_USERNAME }}
        # Optional (recommended) mail server password:
        password: ${{ secrets.EMAIL_PASSWORD }}
        # Required mail subject:
        subject: "Nouveau message depuis le formulaire"
        # Required recipients' addresses:
        to: "jouronlaurent@hotmail.com.com"
        # Required sender full name (address can be skipped):
        from: ${{ github.event.inputs.email }}
        # Optional plain body:
        body: "Prénom: ${{ github.event.inputs.prenom }}\nNom: ${{ github.event.inputs.nom }}\nEmail: ${{ github.event.inputs.email }}\nMessage: ${{ github.event.inputs.txt }}"
        # Optional HTML body read from file:
        html_body: file://README.html

        # Optional unsigned/invalid certificates allowance:
        ignore_cert: true
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
        # Optional attachments:
        attachments: attachments.zip,git.diff,./dist/static/*.js
        # Optional priority: 'high', 'normal' (default) or 'low'
        priority: high
        # Optional nodemailerlog: true/false
        nodemailerlog: false
        # Optional nodemailerdebug: true/false if true lognodem will also be set true
        nodemailerdebug: false